spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev  #开发环境
  application:
    name: microservicespringcloud-config-cdtu-dev
---
spring:
  profiles: test #测试环境
  application: 
    name: microservicespringcloud-config-cdtu-test
#请保存为UTF-8的格式